### ISSUE TITLE
这么棒的主题难道不做一个dark版的吗

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#1]

**Comment by YiNNx** [comment]
5月份有空可能会写~

**Comment by sihaixianyu** [comment]
黑暗模式大佬给安排上，这主题忒好看了！

**Comment by YiNNx** [comment]
> 黑暗模式大佬给安排上，这主题忒好看了！

黑暗模式初版放在`feat/theme-dark`分支，可以来试用看看有什么建议和想法

**Comment by sihaixianyu** [comment]
> > 黑暗模式大佬给安排上，这主题忒好看了！
> 
> 黑暗模式初版放在`feat/theme-dark`分支，可以来试用看看有什么建议和想法

感觉侧边栏和编辑区很难分辨，大佬调一调两个panel颜色，有点色差或者加border。

**Comment by YiNNx** [comment]
Dark 版本已发布 :raised_hands:

**Comment by sihaixianyu** [comment]
舒服了(๑•̀ㅂ•́)و✧，给力！
