### ISSUE TITLE
代码行数显示重叠

### ISSUE THREAD

**Issue by abyss219** [YiNNx/typora-theme-lapis#100]
如图，当代码量很大的时候，会触发行数重叠的情况。刷新或重开Typora有概率修复，不确定切确的触发条件

<img width="829" alt="1" src="https://github.com/user-attachments/assets/a688e79c-3ba9-45cd-beec-fc0e4ae790ae">

<img width="836" alt="1" src="https://github.com/user-attachments/assets/51673860-6839-45d2-a77c-07093302c522">

触发的文件：[java.md](https://github.com/user-attachments/files/16827099/java.md)

**Comment by YiNNx** [comment]
测了一下，看起来是字体导致的，替换 JetBrains Mono 为 JetBrains Mono NL 之后就不会触发这个渲染问题了

**Comment by abyss219** [comment]
我替换成JetBrains Mono NL试了试，还是会出现重叠的情况。但是换成Arial就可以，就是丑了点
感觉还是字体的问题

<img width="831" alt="1" src="https://github.com/user-attachments/assets/1dfc6285-8520-44d7-bc7b-43f34bb37a19">

**Comment by abyss219** [comment]
我看了看，应该是wrapping造成的问题，否则都有概率重叠 #101

**Comment by YiNNx** [comment]
> 我看了看，应该是wrapping造成的问题，否则都有概率重叠 #101

原来是这样！

**Comment by YiNNx** [comment]
solved by #101
