### ISSUE TITLE
代码快中# 和{ 一起用会粘连在一起

### ISSUE THREAD

**Issue by Preke-Li** [YiNNx/typora-theme-lapis#103]
![image](https://github.com/user-attachments/assets/c127229b-6b3a-4c01-a7fd-0534c2d45981)

**Comment by Seeridia** [comment]
这是JetBrains Mono自带的合连字处理
![image](https://github.com/user-attachments/assets/f72239c7-f1fe-47bf-a476-3ef268f568cc)
