### ISSUE TITLE
Unable to display columns when inserting images with embedded HTML

### ISSUE THREAD

**Issue by Chang-Chiang** [YiNNx/typora-theme-lapis#15]
Unable to display columns when inserting images with embedded HTML:
+ html code
![image](https://github.com/YiNNx/typora-theme-lapis/assets/118727083/93e144a2-f907-4a80-9c0f-3267a767b046)

+ display in lapis theme
![image](https://github.com/YiNNx/typora-theme-lapis/assets/118727083/9669f61d-e1b1-43af-aa2a-76f78a443845)

+ display in official github theme
![image](https://github.com/YiNNx/typora-theme-lapis/assets/118727083/e3f9cb7a-822d-41c8-9021-4ce4e262411c)

**Comment by YiNNx** [comment]
This is a known fixed bug - #11, but this fix had not been updated to the release in the download link previously. 
Now the download link version has been updated, and you can also get the latest version of code from the current `master` branch. :raised_hands:
