### ISSUE TITLE
字母p不显示

### ISSUE THREAD

**Issue by ZhaoTim** [YiNNx/typora-theme-lapis#19]
您好，
在使用该主题时，字母p打出来，却不显示~

**Comment by YiNNx** [comment]
是什么操作系统呢

能否提供一下文本样例和截图，感谢~

**Comment by YiNNx** [comment]
是所有字母 p 都看不到吗，其他字母呢
确实是好奇怪的 bug...我这边好像没法复现耶

<img width="627" src="https://github.com/YiNNx/typora-theme-lapis/assets/86649490/4ffc337f-796c-41b4-a1c6-01535065860b">

**Comment by YiNNx** [comment]
> 经过我一顿排查，我似乎发现是字体的原因。
> 
> 我看这个主题的文件下字体文件，点击预览，发现p和q都没有展示~可能
> 
> <img alt="image" width="1069" src="https://user-images.githubusercontent.com/30540533/239751240-87ba0e8e-771b-4019-a68b-3afb04ff7a54.png">

原来这样
估计 https://github.com/YiNNx/typora-theme-lapis/issues/3#issuecomment-1552492529 的问题也同样是字体文件不适配导致的
感谢！

**Comment by YiNNx** [comment]
之前的字体文件版本似乎有点老，从官方仓库重新 build 了一份字体文件，麻烦本地预览看看还有没有显示问题~

[Cantarell-VF-new.zip](https://github.com/YiNNx/typora-theme-lapis/files/11525967/Cantarell-VF-new.zip)
