### ISSUE TITLE
内容目录缩进

### ISSUE THREAD

**Issue by lophter** [YiNNx/typora-theme-lapis#2]
写的非常漂亮的一款主题，字体和排版相得益彰。
如果根据全文生成的内容目录能带自动缩进功能显得更加主次分明，那就无暇了。
同样期待黑色主题。
说声感谢。

**Comment by YiNNx** [comment]
感谢喜欢！

之前自定义正文链接样式时同时影响了TOC链接样式，导致TOC样式没有正常显示。

现在正确的TOC样式已修复至主分支代码中，详见 #6 

黑色主题五月份不忙的话应该会写出来~
