### ISSUE TITLE
代码块行号问题

### ISSUE THREAD

**Issue by Linn3a** [YiNNx/typora-theme-lapis#21]
您好，为什么我的代码块没有像预览效果一样有行号呢

**Comment by YiNNx** [comment]
麻烦提供一下截图和操作系统环境，感谢~

**Comment by Linn3a** [comment]
你好，截图放在附件中，操作系统是win11



***@***.***
 
发件人： YiNN
发送时间： 2023-05-28 12:16
收件人： YiNNx/typora-theme-lapis
抄送： Yuxian; Author
主题： Re: [YiNNx/typora-theme-lapis] 代码块行号问题 (Issue #21)
麻烦提供一下截图和操作系统环境，感谢~
―

**Comment by Linn3a** [comment]
<img width="1280" alt="屏幕截图 2023-05-28 143941" src="https://github.com/YiNNx/typora-theme-lapis/assets/118064332/cd28c25c-0426-4af2-828a-6ec361aa1ac1">
操作系统是win11

**Comment by YiNNx** [comment]
这是 Typora 本身设置所决定的
偏好设置 - Markdown - 代码块 - 显示行号，勾选即可
