### ISSUE TITLE
调整表格行列数时预览区域超出预览框

### ISSUE THREAD

**Issue by fCbDeee** [YiNNx/typora-theme-lapis#24]
win11
Typora version1.6.7

<img width="500" alt="屏幕截图 2023-05-30 143225" src="https://github.com/YiNNx/typora-theme-lapis/assets/116343133/e81cee84-6565-4839-ab86-321da214f628">

**Comment by YiNNx** [comment]
已修复, 详见 #25 :raised_hands:
