### ISSUE TITLE
代码块字符样式改变

### ISSUE THREAD

**Issue by 1244138793** [YiNNx/typora-theme-lapis#27]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/107104714/1d1f4c4e-360f-41c1-b964-7d67a477bc9a)
如图，代码块中的 != 会变成 ≠，xml 里的注释也会直接变成箭头，比较影响观感

**Comment by YiNNx** [comment]
这是代码块使用的字体 JetBrains Mono 自带效果，如果不习惯的话可以在 `lapis.css` 中将 `"JetBrainsMono"` 全局搜索替换为其他本地字体名称，重启 Typora 即可
