### ISSUE TITLE
[建议]行内的图片采用原本的样式

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#29]
**这是出于我自己的应用场景而提出的个人建议，也可以考虑维持原有的样式**

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/de51e229-8479-41b9-8a14-52366988da2a)

> 目前的主题样式

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/194d8147-9f13-4c74-b576-eeb5978bd646)

> 经过修改的主题样式

**Comment by YiNNx** [comment]
已更改, 感谢建议 :raised_hands:
