### ISSUE TITLE
Broken table style in pdf

### ISSUE THREAD

**Issue by YiNNx** [YiNNx/typora-theme-lapis#37]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/86649490/425e1799-6f17-4ef8-a7d2-69fa1a5da5e5)

**Comment by Anyayay** [comment]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/183d0bd5-0860-4497-953f-8ac06d005f03)
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/96f64257-f289-4abe-9eb7-2758313baae4)
Windows 11 （23H2）Typora（1.6.7）下的表格，以及html表格都是可以正常导出的

**Comment by YiNNx** [comment]
那可能是Linux版本的问题，先不管好了
