### ISSUE TITLE
标题中多个链接格式不一致

### ISSUE THREAD

**Issue by zbcdd** [YiNNx/typora-theme-lapis#39]
markdown：
## 4. primes ([moderate](https://pdos.csail.mit.edu/6.828/2021/labs/guidance.html))/([hard](https://pdos.csail.mit.edu/6.828/2021/labs/guidance.html))
会显示成下面这样：
<img width="717" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/52142931/0f04ee15-25a1-41de-b821-c765406b5376">

**Comment by YiNNx** [comment]
这是一个已知bug，二级标题中，当链接/公式和常规文本混杂时会存在样式问题

见 https://github.com/YiNNx/typora-theme-lapis/issues/4#issuecomment-1533675752

与 https://github.com/YiNNx/typora-theme-lapis/issues/10#issuecomment-1553221430

目前并没有找到特别合适的解决办法

**Comment by Anyayay** [comment]
@zbcdd 我在 #40 中已经较好地解决了这个问题，你可以试着看一下如何
![](https://user-images.githubusercontent.com/37764175/251424952-302b4e16-8712-47e4-ba5f-5080f502ac44.png)
