### ISSUE TITLE
标题存在链接时所有原始文字（包括链接等）会直接呈现

### ISSUE THREAD

**Issue by YellowAndGreen** [YiNNx/typora-theme-lapis#4]
如下图所示：
![image](https://user-images.githubusercontent.com/33193090/235913952-4f81989e-6e61-4c96-a856-5bad1bd21f38.png)

**Comment by YellowAndGreen** [comment]
原始的链接文本为：`## ！！！[15. 三数之和](https://leetcode.cn/problems/3sum/)`
经过测试，注释掉以下代码的display可以正常显示：
```
#write h2 span {
 display: inline-block;
 font-weight: bold;
 background: var(--primary-color);
 color: #ffffff;
 padding: 1px 15px 1px;
 border-radius: 4px;
 margin-right: 3px;
}
```

**Comment by YiNNx** [comment]
感谢反馈 :raised_hands:
已修复，详见 #7

**Comment by YiNNx** [comment]
不过本身二级标题样式是通过span来实现的，由于typora span划分限制，`## ！！！[15. 三数之和](https://leetcode.cn/problems/3sum/)` 的显示还是会有一点问题...

![image-20230504041511727](https://cdn.just-plain.fun/img/image-20230504041511727.png)

解决方法是写成`## [！！！15. 三数之和](https://leetcode.cn/problems/3sum/)`

![image-20230504041113451](https://cdn.just-plain.fun/img/image-20230504041113451.png)

**Comment by YellowAndGreen** [comment]
非常感谢😀
