### ISSUE TITLE
lapis-dark的侧边栏字体颜色问题

### ISSUE THREAD

**Issue by FirwoodLin** [YiNNx/typora-theme-lapis#42]
![QQ截图20230712024453.png](https://s2.loli.net/2023/07/12/Ko8qQmpl7GEWMrY.png)

被选中时，文件名称的字体没有变成深色，造成辨识困难

**Comment by FirwoodLin** [comment]
平台 Windows
Typora 版本：1.3.8

**Comment by YiNNx** [comment]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/86649490/7685b6bd-4b03-4246-a456-c80732ee2eaa)
我这边显示是正常的，试试重新下载最新 Release 或更新 Typora 版本？

**Comment by FirwoodLin** [comment]
![Screenshot from 2023-07-12 14-11-13.png](https://s2.loli.net/2023/07/12/s4xYXg3PeByI9t7.png)

看来是 typora 版本问题；1.6.6 ok 了
