### ISSUE TITLE
有序列表的数字"2"无法显示

### ISSUE THREAD

**Issue by ljhao24** [YiNNx/typora-theme-lapis#49]
有序列表的数字"2"无法显示，不知是否是个例？
<img width="332" alt="截屏2023-07-18 23 36 11" src="https://github.com/YiNNx/typora-theme-lapis/assets/76099355/a384c462-0a48-4762-a3db-729e4fa72996">

**Comment by YiNNx** [comment]
试试在 Typora 主题文件夹的 lapis 文件夹中将`Cantarell-VF-new.otf`文件换成下面的？
[Cantarell-VF-new.zip](https://github.com/YiNNx/typora-theme-lapis/files/12135824/Cantarell-VF-new.zip)

**Comment by YiNNx** [comment]
最新的release应该可以正常显示了

**Comment by ljhao24** [comment]
是的，谢谢
