### ISSUE TITLE
表格中行代码的背景颜色

### ISSUE THREAD

**Issue by Deathleaves** [YiNNx/typora-theme-lapis#5]
你好，很漂亮的主题格式，非常感谢。有个问题，表格中如果用``嵌入行代码，显示的背景就还是表格的白色。想请教下该如何修改，让表格中能显示和其他区域的行代码背景颜色一致。
![image](https://user-images.githubusercontent.com/36256719/235928299-99019076-758a-4ea7-abe1-f652bc7b0a66.png)

**Comment by YiNNx** [comment]
这是一个样式 bug，已修复。详见 #8 :raised_hands: 

表格中行代码样式与正文不统一是由于

https://github.com/YiNNx/typora-theme-lapis/blob/181a91c79cb0930bde1a813932f37923526958d5/lapis.css#L244-L260

这里所写的行代码样式只对正文有效，现在改为了

https://github.com/YiNNx/typora-theme-lapis/blob/5496c895b0354636ae6a987435cb689b7d7b0fe2/lapis.css#L248-L261

使行代码样式对全局有效

**Comment by YiNNx** [comment]
这是一个样式 bug，已修复。详见 #8 :raised_hands: 

表格中行代码样式与正文不统一是由于

https://github.com/YiNNx/typora-theme-lapis/blob/181a91c79cb0930bde1a813932f37923526958d5/lapis.css#L244-L260

这里所写的行代码样式只对正文有效，现在改为了

https://github.com/YiNNx/typora-theme-lapis/blob/5496c895b0354636ae6a987435cb689b7d7b0fe2/lapis.css#L248-L261

使行代码样式对全局有效

**Comment by YiNNx** [comment]
这是一个样式 bug，已修复。详见 #8 :raised_hands: 

表格中行代码样式与正文不统一是由于

https://github.com/YiNNx/typora-theme-lapis/blob/181a91c79cb0930bde1a813932f37923526958d5/lapis.css#L244-L260

这里所写的行代码样式只对正文有效，现在改为了

https://github.com/YiNNx/typora-theme-lapis/blob/5496c895b0354636ae6a987435cb689b7d7b0fe2/lapis.css#L248-L261

使行代码样式对全局有效

**Comment by Deathleaves** [comment]
非常感谢👍👍👍
