### ISSUE TITLE
二级标题带下划线无统一背景色问题

### ISSUE THREAD

**Issue by wanlunglau** [YiNNx/typora-theme-lapis#50]
对应的md：
![image](https://github.com/YiNNx/typora-theme-lapis/assets/107366253/3acff76a-e3eb-43a4-9164-0c79cf729707)

## 9. \_\_getattr\_\_、\_\_setattr\_\_等方法

解析后的样子：
![image](https://github.com/YiNNx/typora-theme-lapis/assets/107366253/5ff0a855-7020-4f28-ad5c-792217bac8d8)

**Comment by Anyayay** [comment]
我们目前已在 #47 中着手解决这个问题，你可以提前下载 #47 中的文件进行测试一下
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/91ac737a-c466-49f4-922e-c01ed6df4dea)

**Comment by wanlunglau** [comment]
不是这样的哦新，我是想在标题中 显示 __getattr__ 这样子的 python 魔法方法，需要解析后的格式带双下划线的那种

**Comment by Anyayay** [comment]
抱歉，是我使用了错误的md（我误以为直接复制那行文字就可以了），当前效果如下（也是 #46 已解决的问题，但还未合并）
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/227b66f7-38b3-4852-b006-1c4f66f809fc)

**Comment by wanlunglau** [comment]
好，感谢
