### ISSUE TITLE
标题问题

### ISSUE THREAD

**Issue by aojunhao123** [YiNNx/typora-theme-lapis#54]
![typora theme bug](https://github.com/YiNNx/typora-theme-lapis/assets/82765353/c7a31bd4-849a-4998-b915-eaa79696011d)
当我在无序表格后接二级标题时,大纲中没有相应显示,但二级标题下的三级标题却在大纲中有相应显示.
![typora theme bug](https://github.com/YiNNx/typora-theme-lapis/assets/82765353/2213297b-ea88-4b12-99f7-ecd84690f856)

**Comment by aojunhao123** [comment]
![bug2](https://github.com/YiNNx/typora-theme-lapis/assets/82765353/a3219df5-8379-49f3-a651-86d6d5acb2ee)

**Comment by Anyayay** [comment]
> 参考：
在Windows 11 23H2，typora 1.6.7 & 1.7.0-dev上未能复现该问题
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/f01dd5d5-e183-4c70-b764-603c34a619f7)

尝试更新到最新版本的typora？

**Comment by YiNNx** [comment]
看起来更像是typora的bug，而不是这个主题样式造成的🤔可以尝试更新一下Typora版本
