### ISSUE TITLE
建议调大大纲的间距

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#57]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/8fdceafa-aec1-41b9-9eb5-cff8b5ce45a8)

可以将文件大纲的间距调大至与文件目录差不多的间距

**Comment by YiNNx** [comment]
诶，确实，我之前没打开过大纲可折叠选项，所以只调整了大纲不可折叠时的间距...
