### ISSUE TITLE
建议调整展开箭头的位置

### ISSUE THREAD

**Issue by Anyayay** [YiNNx/typora-theme-lapis#58]
“v”形的展开箭头重心偏下
<img src="https://github.com/YiNNx/typora-theme-lapis/assets/37764175/341bb40b-b5d4-40f7-9529-3d9a33583cba" alt="" style="zoom:5%" />

可以考虑适当往上放一点，使得箭头的中心对齐右边文字的中心，使得更为协调

**Comment by YiNNx** [comment]
欢迎提PR ~
