### ISSUE TITLE
1.1.0版本导出pdf表格线丢失

### ISSUE THREAD

**Issue by lifoo** [YiNNx/typora-theme-lapis#61]
你好 YiNN：
感谢你能够分享这么漂亮的主题～
我在导出pdf时遇到了点问题，导出的pdf表格线丢失了。

下面是即时显示时的效果。
<img width="873" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/4233725/9f3244bd-20cc-4524-a7cf-8f283a1a74cb">
导出的pdf效果如下：
<img width="1006" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/4233725/badbe5fc-868e-4077-865e-a29896514010">

我尝试修改了一下css文件，将所有table.md-table修改为table，出来的效果如下，对我来说是满足要求了，不过我对css的语法不熟悉，不确定是否会有其他影响？所以还是希望你能出个权威点的解决方案。
<img width="957" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/4233725/ee1d2d48-1c01-4120-bfa9-a759963427f3">

**Comment by YiNNx** [comment]
> 我尝试修改了一下css文件，将所有table.md-table修改为table

看起来确实是这样！有兴趣提个PR吗

**Comment by Episode233** [comment]
我的还是存在问题：
md如下
![image](https://github.com/user-attachments/assets/950ccc58-ca06-4641-b567-c2f5a008161a)
pdf如下
![image](https://github.com/user-attachments/assets/0b4fb0cc-e825-4d4e-b7c3-9c7b56d989cf)
源文本如下
![image](https://github.com/user-attachments/assets/464a3bef-3990-47cb-8dd9-d2e2c12acc06)
