### ISSUE TITLE
设置主题后打开文档很卡

### ISSUE THREAD

**Issue by chiristing** [YiNNx/typora-theme-lapis#64]
设置主题后打开文档很卡是为啥呢，删除别的主题了还是很卡，就打开那一会会卡几秒钟。

**Comment by YiNNx** [comment]
请问是什么系统和Typora版本呢

是切换文档也会卡吗？我这边打开Typora只要加载一两秒的样子，切换文档也不卡诶

**Comment by chiristing** [comment]
是win10 64位滴，typro是0.9.93 ，切换并不会卡，就是每次新打开一个文档就会卡，打开之后就不再卡了

**Comment by chiristing** [comment]
也可能是我typro版本太低？emmm

**Comment by YiNNx** [comment]
那应该不是样式代码的问题...:thinking: 可能是Typora读取样式文件发生的卡顿

**Comment by chiristing** [comment]
嗯，可能是的

**Comment by YiNNx** [comment]
我这边复现不太不出来诶，打开其他主题和Lapis一样也会有一两秒的加载，但都算不上卡顿

**Comment by chiristing** [comment]
哦哦，那我换一个typro版本试一试，嘿嘿
