### ISSUE TITLE
双数序号导出PDF显示不全

### ISSUE THREAD

**Issue by jerfain** [YiNNx/typora-theme-lapis#68]
<img width="1087" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/69144012/b995d1de-5421-4943-8591-2a913360f696">
是MAC平台的typora

**Comment by YiNNx** [comment]
遮挡问题在我自己设备上复现不出来，所以可能暂时没办法修复，欢迎提PR
表格边框的问题现在应该已经修复了，试试clone一下最新代码？
参见 #63 #66

**Comment by jerfain** [comment]
好的，刚刚试了表格问题已经解决啦。关于序号导出遮挡的问题我自己在list里把padding-left修改成25px就解决了。非常感谢！
