### ISSUE TITLE
添加特殊引用样式

### ISSUE THREAD

**Issue by LZerro** [YiNNx/typora-theme-lapis#70]
怎么才能够打出信息引用与警告引用，我现在只能打出普通引用

**Comment by YiNNx** [comment]
Typora 本身并没有支持特殊引用，lapis 也没有添加特殊引用样式，所以确实只能打出普通引用。
如果想给 lapis 增加特殊引用样式，欢迎提 PR

**Comment by Anyayay** [comment]
@YiNNx @LZerro 
以前没有试过，不过现在typora好像是可以打得出来的
```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/c51e0bfc-fe85-4024-9c5b-25cf7367e3bf)
只不过lapis并没有做这些样式

**Comment by YiNNx** [comment]
是的，Typora 最新 1.8.2-dev 版本里新增 - Support github style alert.

接下来会考虑给 lapis 增加对应样式
