### ISSUE TITLE
导出pdf表格无法正常显示

### ISSUE THREAD

**Issue by Pacooral** [YiNNx/typora-theme-lapis#71]
![image](https://github.com/YiNNx/typora-theme-lapis/assets/96587158/5fd5ed22-259c-4a02-a6bc-1277b4710242)
![image](https://github.com/YiNNx/typora-theme-lapis/assets/96587158/9a2af104-8662-42be-a26e-95a4bac1e21a)

**Comment by RiceShowerDev** [comment]
这个问题怎么解决的呢

**Comment by YiNNx** [comment]
拉一下最新代码，这个bug应该已经在 #63 修好了

**Comment by RiceShowerDev** [comment]
这是来自邹乐颜（Zou Leyan）邮箱的自动回复邮件。 您好，您的邮件我已收到，如需回复我将尽快回复！
