### ISSUE TITLE
当导出HTML时，Table的样式丢失的问题

### ISSUE THREAD

**Issue by chenyilun153** [YiNNx/typora-theme-lapis#73]
window平台，导出HTML时，Table没有边框线，但是在Typora中是正常显示的！

**Comment by chenyilun153** [comment]
table.md-table  -- > table 
去掉.md-table后样式生效了！

**Comment by YiNNx** [comment]
这是一个已经修好的 bug，详见 #63  和 #66 
只去掉md-table会导致 #66 的情况，可以直接拉取主分支的最新代码，是已经修复的版本，只是还没有发 Release
