### ISSUE TITLE
导出PDF时图片显示异常

### ISSUE THREAD

**Issue by Just-do-st** [YiNNx/typora-theme-lapis#77]
typora中正常的图片

![image](https://github.com/YiNNx/typora-theme-lapis/assets/70735335/6fc6256d-5b71-436a-9cac-5ad5a2dda0ca)

导出为PDF后的图片失真严重

![image](https://github.com/YiNNx/typora-theme-lapis/assets/70735335/ad9ddea2-064a-4b21-a81e-169ebaa0c22c)

**Comment by Just-do-st** [comment]
请问这个问题会修复吗

**Comment by YiNNx** [comment]
非常抱歉可能暂时不会修复，目前考虑在后续版本中直接移除图片的阴影和圆角样式，因为有些影响部分类型图片的显示效果

**Comment by Just-do-st** [comment]
好的，感谢
