### ISSUE TITLE
导出表格式格式混乱，且没有表格线

### ISSUE THREAD

**Issue by CrashBugger** [YiNNx/typora-theme-lapis#79]
导出表格式格式混乱，且没有表格线

**Comment by YiNNx** [comment]
这是一个已经修好的 bug，详见 https://github.com/YiNNx/typora-theme-lapis/pull/63 和 https://github.com/YiNNx/typora-theme-lapis/issues/66
Release 版本没有更新这个修复，可以拉取一下主分支的代码

**Comment by Anyayay** [comment]
> 这是一个已经修好的 bug，详见 #63 和 #66 Release 版本没有更新这个修复，可以拉取一下主分支的代码

更一下Release吧，最近这个问题提了很多遍了

**Comment by YiNNx** [comment]
> 更一下Release吧，最近这个问题提了很多遍了

有道理

**Comment by YiNNx** [comment]
已更新 Release

**Comment by CrashBugger** [comment]
Thank you!
