### ISSUE TITLE
文档内某些字符或者数字无法显示

### ISSUE THREAD

**Issue by 3056836976** [YiNNx/typora-theme-lapis#82]
<img width="1728" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/80240239/beb2864b-154c-4ed1-99c5-4d592955e61f">
<img width="1728" alt="Snipaste_2023-11-28_16-05-46" src="https://github.com/YiNNx/typora-theme-lapis/assets/80240239/62b3b346-7b9b-495b-a84c-b0f314f9e2e4">

**Comment by YiNNx** [comment]
最新版本应该不会有这个显示问题？可以检查一下主题文件里面 lapis/Cantarell-VF-fixed.otf 是不是带有这个 fixed 后缀
