### ISSUE TITLE
R中<-显示错误的问题

### ISSUE THREAD

**Issue by derqian** [YiNNx/typora-theme-lapis#89]
code:
`pred <- predict(step2, test_df, type = 'response')`
但是实际显示 成了一个向左的箭头

<img width="409" alt="image" src="https://github.com/YiNNx/typora-theme-lapis/assets/116062643/8c461361-120b-44b5-820d-2a2c411844a3">

**Comment by YiNNx** [comment]
这是代码字体 jetbrains mono 自带的显示效果，并非显示问题

**Comment by derqian** [comment]
> 这是代码字体 jetbrains mono 自带的显示效果，并非显示问题

有什么办法避免这个显示吗?

**Comment by YiNNx** [comment]
https://github.com/YiNNx/typora-theme-lapis/blob/c9225cf77deb1a05cfdbb08ebb9f5448deb7364c/lapis.css#L52-L57

注释掉这几行就行
