### ISSUE TITLE
checkbox显示有点问题

### ISSUE THREAD

**Issue by wdawii** [YiNNx/typora-theme-lapis#9]
圆圈的上面还有一个线条，可能是被挡住的小方框

<img width="355" alt="image" src="https://user-images.githubusercontent.com/107685514/236454518-edbc2c54-880b-4395-bc56-ec1bbd4ea48c.png">

**Comment by YiNNx** [comment]
是什么系统呀，我这边 Linux 下 checkbox 样式好像是正常的 :thinking: 

![image](https://user-images.githubusercontent.com/86649490/236455375-99fbf517-0f4b-4bae-8545-eb13c6912a19.png)

**Comment by wdawii** [comment]
mac

**Comment by Anyayay** [comment]
感觉有点偏高？
![image](https://github.com/YiNNx/typora-theme-lapis/assets/37764175/d2ec6830-0989-438e-849e-2e9c98bbd932)

**Comment by wdawii** [comment]
> 

好很多了，谢谢
