### ISSUE TITLE
代码段或图片加载时会有黑框闪现

### ISSUE THREAD

**Issue by Chordrain** [YiNNx/typora-theme-lapis#90]
问题如图：
<img width="1117" alt="issue" src="https://github.com/YiNNx/typora-theme-lapis/assets/102977440/bfac5213-d7f0-4158-85cc-b037365aa384">
解决方案：注释掉下面这句话
<img width="365" alt="fix" src="https://github.com/YiNNx/typora-theme-lapis/assets/102977440/532c7097-32b4-4fc4-ae9a-95662799434a">
不知道这句话的具体用途是什么，但是去掉之后就不会再出现上面的状况，如果改错万分抱歉！

**Comment by YiNNx** [comment]
看起来确实是这一行的问题，可以来提交个 PR

**Comment by Edward-Elric233** [comment]
貌似这个issue还没有提交PR，现在仍旧存在这个问题。注释掉后就不会出现黑框了

**Comment by YiNNx** [comment]
Fixed by #91
