### ISSUE TITLE
关闭连字（ligature）

### ISSUE THREAD

**Issue by theSprog** [YiNNx/typora-theme-lapis#92]
在代码块中输入 >= 是会自动连成数学那种写法，我不想要这个，请问怎么配置关闭它。

**Comment by YiNNx** [comment]
可参考 https://github.com/YiNNx/typora-theme-lapis/issues/27#issuecomment-1578188519

**Comment by theSprog** [comment]
谢谢，但我挺喜欢这个字体的，不太想更换。
我只是想关闭字体的连字特效😁

**Comment by YiNNx** [comment]
可以自行安装 JetBrains Mono NL (JetBrains Mono 的不练字版本)，然后再对样式文件的代码字体进行替换~

**Comment by theSprog** [comment]
Ok，Thanks~
