### ISSUE TITLE
特定MATLAB代码显示错误，出现底纹

### ISSUE THREAD

**Issue by afterglow-dotcom** [YiNNx/typora-theme-lapis#98]
如图，`parameters.kind`中的`.`在lapis和lapis dark主题下出现了底纹，更换其他主题后并未出现此现象，在lapis和lapis dark主题下修改该代码块的代码语言也不会出现此现象，目前仅发现对于lapis和lapis中matlab代码块会出现问题

- lapis

<img width="903" alt="image" src="https://github.com/user-attachments/assets/ec622eb5-b089-4c66-b232-7f5c70df54df">

- lapis dark

<img width="905" alt="image" src="https://github.com/user-attachments/assets/c3ccabfe-dcbe-431f-8e8e-4b10880e4da5">

- github

<img width="978" alt="image" src="https://github.com/user-attachments/assets/8c9f32bc-e5cc-4763-9f8d-6202282a7b2d">

**Comment by YiNNx** [comment]
看起来是因为`.`被代码块识别为 error 了，因此显示了 lapis 中 error 对应的样式（粉色底纹）
p3 的 `.` 也显示为了红色，对应 github 主题的 error 样式
